In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML
display(HTML("<style>.container { width:98% !important; }</style>"))

In [2]:
salaeCSVfile = '/Users/johnmarshall/Documents/Analysis/miniscope_analysis/miniscope_T_maze/m328/raw_328.csv'
salaeData = pd.read_csv(salaeCSVfile)
timestampfileSession1 = pd.read_table('/Users/johnmarshall/Documents/Analysis/miniscope_analysis/miniscope_T_maze/m328/timeStampsMiniscope_16_44_25.csv', delimiter=',')
timestampfileSession2 = pd.read_table('/Users/johnmarshall/Documents/Analysis/miniscope_analysis/miniscope_T_maze/m328/timeStampsMiniscope_17_56_20.csv', delimiter=',')

In [3]:
salaeData

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,Channel 9,Channel 10,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15
0,0.000000,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,75.184965,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,75.219546,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,75.252180,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,75.285787,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231108,8103.506708,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
231109,8103.539440,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
231110,8103.573055,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
231111,8103.607342,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
231112,8126.054400,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [4]:
#Match miniscope imaging activity with salae activity

In [5]:
miniscope_full_runtime_file = pd.concat([timestampfileSession1, timestampfileSession2], ignore_index=True)
miniscope_full_runtime_file

        Frame Number  Time Stamp (ms)  Buffer Index
0                  0               -5             0
1                  1               30             0
2                  2               62             0
3                  3               96             0
4                  4              132             0
...              ...              ...           ...
229686        110456          3714244             0
229687        110457          3714277             0
229688        110458          3714313             0
229689        110459          3714345             0
229690        110460          3714381             0

[229691 rows x 3 columns]

In [6]:
## find rows where channel 12 TTL is alternating 
rows_withMiniscopeTTL = salaeData.loc[
    (salaeData['Channel 12'] != salaeData['Channel 12'].shift(-1)) &
    (salaeData['Channel 12'] == salaeData['Channel 12'].shift(-2))
]
rows_withMiniscopeTTL = rows_withMiniscopeTTL[1:]
rows_withMiniscopeTTL

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,Channel 9,Channel 10,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15
1,75.184965,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,75.219546,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,75.252180,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,75.285787,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
5,75.319905,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231105,8103.405960,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
231106,8103.438692,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
231107,8103.472232,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
231108,8103.506708,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
231109,8103.539440,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
## get delta time in ms between salae samples 
rows_withMiniscopeTTL['Time Delta [ms]'] = abs(rows_withMiniscopeTTL['Time [s]'] - rows_withMiniscopeTTL['Time [s]'].shift(-1))
rows_withMiniscopeTTL['Time Delta [ms]'] = rows_withMiniscopeTTL['Time Delta [ms]']*1000

In [8]:
rows_withMiniscopeTTL

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,Channel 9,Channel 10,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15,Time Delta [ms]
1,75.184965,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34.581
2,75.219546,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,32.634
3,75.252180,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.607
4,75.285787,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,34.118
5,75.319905,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231105,8103.405960,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32.732
231106,8103.438692,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,33.540
231107,8103.472232,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34.476
231108,8103.506708,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,32.732
231109,8103.539440,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN

In [9]:
# need these rows where ['Time Delta [s]'] is between 30 to 40 ms this will return periods where the miniscope is actually "recording", 
# i.e. TTLs are recorded at a consistent frequency
MiniscopeRecordingPeriods = rows_withMiniscopeTTL[(rows_withMiniscopeTTL['Time Delta [ms]'] < 40 ) & (rows_withMiniscopeTTL['Time Delta [ms]'] > 30)]
MiniscopeRecordingPeriods['TTL Gap [s]'] = abs(MiniscopeRecordingPeriods['Time [s]'] - MiniscopeRecordingPeriods['Time [s]'].shift(-1))

In [10]:
# between recording periods there will be a large spike here (pause when no consistent TTL is recorded)
MiniscopeRecordingPeriods[MiniscopeRecordingPeriods['TTL Gap [s]'] > 10]

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,Channel 9,Channel 10,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15,Time Delta [ms],TTL Gap [s]
119955,4083.331521,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.11,305.923485

In [11]:
# this finds that long pause 
maxGap = MiniscopeRecordingPeriods.loc[
    MiniscopeRecordingPeriods['TTL Gap [s]'] > 10,
    'TTL Gap [s]'
].idxmax()
maxGap
pos = MiniscopeRecordingPeriods.index.get_loc(maxGap)
# "pos" here is the salae sample that should match the end of the 1st miniscope recording, start of 1st recording is 1st salae sample 
# "pos" + 1 should be the first frame of the 2nd miniscope recording , end of 2nd miniscope recording should be last sample of "MiniscopeRecordingPeriods" data frame 
pos

117305

In [12]:
## now need to match up miniscope and account for sampling frequency difference 
#miniscope recording 1
salaeSamplesMiniscopeRecording_1 = MiniscopeRecordingPeriods.iloc[0:pos]
#miniscope recording 2
salaeSamplesMiniscopeRecording_2 = MiniscopeRecordingPeriods.iloc[pos+1:]

salaeSamplesMiniscopeRecording_1

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,Channel 9,Channel 10,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15,Time Delta [ms],TTL Gap [s]
1,75.184965,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34.581,0.034581
2,75.219546,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,32.634,0.032634
3,75.252180,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.607,0.033607
4,75.285787,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,34.118,0.034118
5,75.319905,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.355,0.033355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119950,4083.163230,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,33.376,0.033376
119951,4083.196606,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34.513,0.034513
119952,4083.231119,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,32.687,0.032687
119953,4083.263806,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.609,0.033609
119954,4083.297415,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,34.106,0.034106

In [13]:
salaeSamplesMiniscopeRecording_1 = MiniscopeRecordingPeriods.iloc[0:pos].copy()

start_time = timestampfileSession1['Time Stamp (ms)'].iloc[0]

salaeSamplesMiniscopeRecording_1['Salae Miniscope Time (ms)'] = (
    salaeSamplesMiniscopeRecording_1['Time [s]'] - salaeSamplesMiniscopeRecording_1['Time [s]'].iloc[0]
) * 1000
salaeSamplesMiniscopeRecording_1.loc[
    salaeSamplesMiniscopeRecording_1.index[0], 'Salae Miniscope Time (ms)'
] = start_time
#Adjusts Salae timing to miniscope timing

salaeSamplesMiniscopeRecording_1 = pd.concat([
    salaeSamplesMiniscopeRecording_1.reset_index(drop=True),
    timestampfileSession1[['Frame Number', 'Time Stamp (ms)']].reset_index(drop=True)
], axis=1)

In [14]:
len(timestampfileSession1)-117305

1925

In [15]:
salaeSamplesMiniscopeRecording_1[-1930:-1920]

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,...,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15,Time Delta [ms],TTL Gap [s],Salae Miniscope Time (ms),Frame Number,Time Stamp (ms)
117300,4083.163230,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,33.376,0.033376,4007978.265,117300,3943448
117301,4083.196606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,34.513,0.034513,4008011.641,117301,3943482
117302,4083.231119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,32.687,0.032687,4008046.154,117302,3943516
117303,4083.263806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,33.609,0.033609,4008078.841,117303,3943551
117304,4083.297415,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,34.106,0.034106,4008112.450,117304,3943583
117305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117305,3943616
117306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117306,3943649
117307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117307,3943683
117308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117308,3943717
117309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117309,3943752

In [16]:
# original approach: found miniscope frame where the 'Time Stamp (ms)' was closest preceeding value to the 'Salae Miniscope Time (ms)' value
salaeSamplesMiniscopeRecording_1['Corresponding Miniscope Frame'] = salaeSamplesMiniscopeRecording_1['Salae Miniscope Time (ms)'].apply(
    lambda x: salaeSamplesMiniscopeRecording_1.loc[salaeSamplesMiniscopeRecording_1['Time Stamp (ms)'] <= x, 'Frame Number'].max()
)


#alternative approach, find the miniscope frame where the 'Time Stamp (ms)' was closest in absolute value to the
#'Salae Miniscope Time (ms)' value , needs to have the "np.nan if pd.isna(x)" for the rows where 'Salae Miniscope Time (ms)' is NaN
salaeSamplesMiniscopeRecording_1['Corresponding Miniscope Frame'] = (
    salaeSamplesMiniscopeRecording_1['Salae Miniscope Time (ms)'].apply(
        lambda x: np.nan if pd.isna(x) else salaeSamplesMiniscopeRecording_1.loc[
            (salaeSamplesMiniscopeRecording_1['Time Stamp (ms)'] - x).abs().idxmin(),
            'Frame Number'
        ]
    )
)

In [ ]:
salaeSamplesMiniscopeRecording_1Truncated = salaeSamplesMiniscopeRecording_1[salaeSamplesMiniscopeRecording_1['Corresponding Miniscope Frame'].notna()] 
salaeSamplesMiniscopeRecording_1Truncated

In [ ]:
salaeSamplesMiniscopeRecording_1
salaeSamplesMiniscopeRecording_1.to_csv('salaeSamplesMiniscopeRecording_1.csv')

In [ ]:
salaeSamplesMiniscopeRecording_2 = MiniscopeRecordingPeriods.iloc[pos+1:]
salaeSamplesMiniscopeRecording_2

In [ ]:
start_time = timestampfileSession2['Time Stamp (ms)'].iloc[0]


salaeSamplesMiniscopeRecording_2['Salae Miniscope Time (ms)'] = (
    salaeSamplesMiniscopeRecording_2['Time [s]'] - salaeSamplesMiniscopeRecording_2['Time [s]'].iloc[0]
) * 1000
salaeSamplesMiniscopeRecording_2.loc[
    salaeSamplesMiniscopeRecording_2.index[0], 'Salae Miniscope Time (ms)'
] = start_time
#Adjusts Salae timing to miniscope timing

salaeSamplesMiniscopeRecording_2 = salaeSamplesMiniscopeRecording_2.drop(columns=['Time Stamp (ms)', 'Frame Number'], errors='ignore')

salaeSamplesMiniscopeRecording_2 = pd.concat([
    salaeSamplesMiniscopeRecording_2.reset_index(drop=True),
    timestampfileSession2[['Frame Number', 'Time Stamp (ms)']].reset_index(drop=True)
], axis=1)

In [ ]:
print(len(salaeSamplesMiniscopeRecording_2))  # salae rows
print(len(timestampfileSession2))

In [ ]:
salaeSamplesMiniscopeRecording_2 = salaeSamplesMiniscopeRecording_2.dropna(subset=['Salae Miniscope Time (ms)'])

salaeSamplesMiniscopeRecording_2['Corresponding Miniscope Frame'] = salaeSamplesMiniscopeRecording_2['Salae Miniscope Time (ms)'].apply(
    lambda x: salaeSamplesMiniscopeRecording_2.loc[salaeSamplesMiniscopeRecording_2['Time Stamp (ms)'] <= x, 'Frame Number'].max()
)

In [ ]:
salaeSamplesMiniscopeRecording_2
salaeSamplesMiniscopeRecording_2.to_csv('salaeSamplesMiniscopeRecording_2.csv')