In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML
display(HTML("<style>.container { width:98% !important; }</style>"))

In [3]:
salaeCSVfile = '/Users/johnmarshall/Documents/Analysis/miniscope_analysis/miniscope_T_maze/m328/raw_328.csv'
salaeData = pd.read_csv(salaeCSVfile)
timestampfileSession1 = pd.read_table('/Users/johnmarshall/Documents/Analysis/miniscope_analysis/miniscope_T_maze/m328/timeStampsMiniscope_16_44_25.csv', delimiter=',')
timestampfileSession2 = pd.read_table('/Users/johnmarshall/Documents/Analysis/miniscope_analysis/miniscope_T_maze/m328/timeStampsMiniscope_17_56_20.csv', delimiter=',')

In [4]:
salaeData

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,Channel 9,Channel 10,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15
0,0.000000,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,75.184965,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,75.219546,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,75.252180,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,75.285787,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231108,8103.506708,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
231109,8103.539440,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
231110,8103.573055,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
231111,8103.607342,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
231112,8126.054400,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [5]:
#Match miniscope imaging activity with salae activity

In [6]:
miniscope_full_runtime_file = pd.concat([timestampfileSession1, timestampfileSession2], ignore_index=True)
miniscope_full_runtime_file

        Frame Number  Time Stamp (ms)  Buffer Index
0                  0               -5             0
1                  1               30             0
2                  2               62             0
3                  3               96             0
4                  4              132             0
...              ...              ...           ...
229686        110456          3714244             0
229687        110457          3714277             0
229688        110458          3714313             0
229689        110459          3714345             0
229690        110460          3714381             0

[229691 rows x 3 columns]

In [7]:
## find rows where channel 12 TTL is alternating 
rows_withMiniscopeTTL = salaeData.loc[
    (salaeData['Channel 12'] != salaeData['Channel 12'].shift(-1)) &
    (salaeData['Channel 12'] == salaeData['Channel 12'].shift(-2))
]
rows_withMiniscopeTTL = rows_withMiniscopeTTL[1:]
rows_withMiniscopeTTL

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,Channel 9,Channel 10,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15
1,75.184965,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,75.219546,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,75.252180,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,75.285787,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
5,75.319905,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231105,8103.405960,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
231106,8103.438692,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
231107,8103.472232,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
231108,8103.506708,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
231109,8103.539440,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [8]:
## get delta time in ms between salae samples 
rows_withMiniscopeTTL['Time Delta [ms]'] = abs(rows_withMiniscopeTTL['Time [s]'] - rows_withMiniscopeTTL['Time [s]'].shift(-1))
rows_withMiniscopeTTL['Time Delta [ms]'] = rows_withMiniscopeTTL['Time Delta [ms]']*1000

In [9]:
rows_withMiniscopeTTL

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,Channel 9,Channel 10,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15,Time Delta [ms]
1,75.184965,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34.581
2,75.219546,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,32.634
3,75.252180,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.607
4,75.285787,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,34.118
5,75.319905,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231105,8103.405960,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32.732
231106,8103.438692,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,33.540
231107,8103.472232,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34.476
231108,8103.506708,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,32.732
231109,8103.539440,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN

In [10]:
# need these rows where ['Time Delta [s]'] is between 30 to 40 ms this will return periods where the miniscope is actually "recording", 
# i.e. TTLs are recorded at a consistent frequency
MiniscopeRecordingPeriods = rows_withMiniscopeTTL[(rows_withMiniscopeTTL['Time Delta [ms]'] < 40 ) & (rows_withMiniscopeTTL['Time Delta [ms]'] > 30)]
MiniscopeRecordingPeriods['TTL Gap [s]'] = abs(MiniscopeRecordingPeriods['Time [s]'] - MiniscopeRecordingPeriods['Time [s]'].shift(-1))

In [11]:
# between recording periods there will be a large spike here (pause when no consistent TTL is recorded)
MiniscopeRecordingPeriods[MiniscopeRecordingPeriods['TTL Gap [s]'] > 10]

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,Channel 9,Channel 10,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15,Time Delta [ms],TTL Gap [s]
119955,4083.331521,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.11,305.923485

In [12]:
# this finds that long pause 
maxGap = MiniscopeRecordingPeriods.loc[
    MiniscopeRecordingPeriods['TTL Gap [s]'] > 10,
    'TTL Gap [s]'
].idxmax()
maxGap
pos = MiniscopeRecordingPeriods.index.get_loc(maxGap)
# "pos" here is the salae sample that should match the end of the 1st miniscope recording, start of 1st recording is 1st salae sample 
# "pos" + 1 should be the first frame of the 2nd miniscope recording , end of 2nd miniscope recording should be last sample of "MiniscopeRecordingPeriods" data frame 
pos

117305

In [13]:
## now need to match up miniscope and account for sampling frequency difference 
#miniscope recording 1
salaeSamplesMiniscopeRecording_1 = MiniscopeRecordingPeriods.iloc[0:pos]
#miniscope recording 2
salaeSamplesMiniscopeRecording_2 = MiniscopeRecordingPeriods.iloc[pos+1:]

salaeSamplesMiniscopeRecording_1

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,Channel 9,Channel 10,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15,Time Delta [ms],TTL Gap [s]
1,75.184965,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34.581,0.034581
2,75.219546,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,32.634,0.032634
3,75.252180,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.607,0.033607
4,75.285787,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,34.118,0.034118
5,75.319905,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.355,0.033355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119950,4083.163230,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,33.376,0.033376
119951,4083.196606,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34.513,0.034513
119952,4083.231119,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,32.687,0.032687
119953,4083.263806,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.609,0.033609
119954,4083.297415,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,34.106,0.034106

In [14]:
salaeSamplesMiniscopeRecording_1 = MiniscopeRecordingPeriods.iloc[0:pos].copy()

start_time = timestampfileSession1['Time Stamp (ms)'].iloc[0]

salaeSamplesMiniscopeRecording_1['Salae Miniscope Time (ms)'] = (
    salaeSamplesMiniscopeRecording_1['Time [s]'] - salaeSamplesMiniscopeRecording_1['Time [s]'].iloc[0]
) * 1000
salaeSamplesMiniscopeRecording_1.loc[
    salaeSamplesMiniscopeRecording_1.index[0], 'Salae Miniscope Time (ms)'
] = start_time
#Adjusts Salae timing to miniscope timing

salaeSamplesMiniscopeRecording_1 = pd.concat([
    salaeSamplesMiniscopeRecording_1.reset_index(drop=True),
    timestampfileSession1[['Frame Number', 'Time Stamp (ms)']].reset_index(drop=True)
], axis=1)

In [15]:
len(timestampfileSession1)-117305

1925

In [16]:
salaeSamplesMiniscopeRecording_1[-1930:-1920]

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,...,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15,Time Delta [ms],TTL Gap [s],Salae Miniscope Time (ms),Frame Number,Time Stamp (ms)
117300,4083.163230,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,33.376,0.033376,4007978.265,117300,3943448
117301,4083.196606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,34.513,0.034513,4008011.641,117301,3943482
117302,4083.231119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,32.687,0.032687,4008046.154,117302,3943516
117303,4083.263806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,33.609,0.033609,4008078.841,117303,3943551
117304,4083.297415,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,34.106,0.034106,4008112.450,117304,3943583
117305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117305,3943616
117306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117306,3943649
117307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117307,3943683
117308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117308,3943717
117309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117309,3943752

In [17]:
# original approach: found miniscope frame where the 'Time Stamp (ms)' was closest preceeding value to the 'Salae Miniscope Time (ms)' value
salaeSamplesMiniscopeRecording_1['Corresponding Miniscope Frame'] = salaeSamplesMiniscopeRecording_1['Salae Miniscope Time (ms)'].apply(
    lambda x: salaeSamplesMiniscopeRecording_1.loc[salaeSamplesMiniscopeRecording_1['Time Stamp (ms)'] <= x, 'Frame Number'].max()
)


#alternative approach, find the miniscope frame where the 'Time Stamp (ms)' was closest in absolute value to the
#'Salae Miniscope Time (ms)' value , needs to have the "np.nan if pd.isna(x)" for the rows where 'Salae Miniscope Time (ms)' is NaN
salaeSamplesMiniscopeRecording_1['Corresponding Miniscope Frame'] = (
    salaeSamplesMiniscopeRecording_1['Salae Miniscope Time (ms)'].apply(
        lambda x: np.nan if pd.isna(x) else salaeSamplesMiniscopeRecording_1.loc[
            (salaeSamplesMiniscopeRecording_1['Time Stamp (ms)'] - x).abs().idxmin(),
            'Frame Number'
        ]
    )
)

In [18]:
salaeSamplesMiniscopeRecording_1Truncated = salaeSamplesMiniscopeRecording_1[salaeSamplesMiniscopeRecording_1['Corresponding Miniscope Frame'].notna()] 
salaeSamplesMiniscopeRecording_1Truncated

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,...,Channel 12,Channel 13,Channel 14,Channel 15,Time Delta [ms],TTL Gap [s],Salae Miniscope Time (ms),Frame Number,Time Stamp (ms),Corresponding Miniscope Frame
0,75.184965,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,34.581,0.034581,-5.000,0,-5,0.0
1,75.219546,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,32.634,0.032634,34.581,1,30,1.0
2,75.252180,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,33.607,0.033607,67.215,2,62,2.0
3,75.285787,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,34.118,0.034118,100.822,3,96,3.0
4,75.319905,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,33.355,0.033355,134.940,4,132,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117300,4083.163230,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,33.376,0.033376,4007978.265,117300,3943448,119220.0
117301,4083.196606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,34.513,0.034513,4008011.641,117301,3943482,119221.0
117302,4083.231119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,32.687,0.032687,4008046.154,117302,3943516,119222.0
117303,4083.263806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,33.609,0.033609,4008078.841,117303,3943551,119223.0
117304,4083.297415,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,34.106,0.034106,4008112.450,117304,3943583,119224.0

In [19]:
salaeSamplesMiniscopeRecording_1
salaeSamplesMiniscopeRecording_1.to_csv('salaeSamplesMiniscopeRecording_1.csv')

In [20]:
salaeSamplesMiniscopeRecording_2 = MiniscopeRecordingPeriods.iloc[pos+1:]
salaeSamplesMiniscopeRecording_2

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,Channel 9,Channel 10,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15,Time Delta [ms],TTL Gap [s]
120029,4389.255006,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32.972,0.032972
120030,4389.287978,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,33.601,0.033601
120031,4389.321579,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.805,0.033805
120032,4389.355384,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,33.414,0.033414
120033,4389.388798,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33.601,0.033601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231104,8103.371397,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,34.563,0.034563
231105,8103.405960,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32.732,0.032732
231106,8103.438692,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,33.540,0.033540
231107,8103.472232,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34.476,0.034476
231108,8103.506708,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,32.732,NaN

In [21]:
start_time = timestampfileSession2['Time Stamp (ms)'].iloc[0]


salaeSamplesMiniscopeRecording_2['Salae Miniscope Time (ms)'] = (
    salaeSamplesMiniscopeRecording_2['Time [s]'] - salaeSamplesMiniscopeRecording_2['Time [s]'].iloc[0]
) * 1000
salaeSamplesMiniscopeRecording_2.loc[
    salaeSamplesMiniscopeRecording_2.index[0], 'Salae Miniscope Time (ms)'
] = start_time
#Adjusts Salae timing to miniscope timing

salaeSamplesMiniscopeRecording_2 = salaeSamplesMiniscopeRecording_2.drop(columns=['Time Stamp (ms)', 'Frame Number'], errors='ignore')

salaeSamplesMiniscopeRecording_2 = pd.concat([
    salaeSamplesMiniscopeRecording_2.reset_index(drop=True),
    timestampfileSession2[['Frame Number', 'Time Stamp (ms)']].reset_index(drop=True)
], axis=1)

In [22]:
print(len(salaeSamplesMiniscopeRecording_2))  # salae rows
print(len(timestampfileSession2))

110461
110461

In [23]:
salaeSamplesMiniscopeRecording_2 = salaeSamplesMiniscopeRecording_2.dropna(subset=['Salae Miniscope Time (ms)'])

salaeSamplesMiniscopeRecording_2['Corresponding Miniscope Frame'] = salaeSamplesMiniscopeRecording_2['Salae Miniscope Time (ms)'].apply(
    lambda x: salaeSamplesMiniscopeRecording_2.loc[salaeSamplesMiniscopeRecording_2['Time Stamp (ms)'] <= x, 'Frame Number'].max()
)

In [24]:
salaeSamplesMiniscopeRecording_2
salaeSamplesMiniscopeRecording_2.to_csv('salaeSamplesMiniscopeRecording_2.csv')

In [25]:
# --- Load aligned salae session 1 ---

salae_1 = pd.read_csv('salaeSamplesMiniscopeRecording_1.csv')

# --- Find Ch11 rising edges ---

ch11_rises = salae_1[
    (salae_1["Channel 11"] == 1) & (salae_1["Channel 11"].shift(1) == 0)
]["Time [s]"].values

# --- Find Ch6 falling edges (delay start) ---

ch6_falling = salae_1[
    (salae_1["Channel 6"] == 0) & (salae_1["Channel 6"].shift(1) == 1)
]["Time [s]"].values

# --- Find last Ch3 or Ch4 rising edge before each Ch6 falling edge (which arm was forced) ---

ch3_rising = salae_1[
    (salae_1["Channel 3"] == 1) & (salae_1["Channel 3"].shift(1) == 0)
][["Time [s]"]].copy()
ch3_rising["forced_side"] = "left"

ch4_rising = salae_1[
    (salae_1["Channel 4"] == 1) & (salae_1["Channel 4"].shift(1) == 0)
][["Time [s]"]].copy()
ch4_rising["forced_side"] = "right"

ch34_rising = pd.concat([ch3_rising, ch4_rising]).sort_values("Time [s]")

# --- For each Ch11 rising edge, find the preceding Ch6 falling edge ---
# and classify as a real delay period (5s or 30s only)

delay_trials = []
trial_number = 0

for t11 in ch11_rises:
    # find last Ch6 falling edge before this Ch11
    preceding_ch6 = ch6_falling[ch6_falling < t11]
    if len(preceding_ch6) == 0:
        continue

    delay_start_time = preceding_ch6[-1]
    gap = t11 - delay_start_time

    # only keep real delay periods
    if 4 < gap < 8:
        delay_type = 5
    elif 25 < gap < 35:
        delay_type = 30
    else:
        continue  # skip 0s trials

    # find last Ch3/Ch4 rising edge before the Ch6 falling edge
    preceding_ch34 = ch34_rising[ch34_rising["Time [s]"] < delay_start_time]
    if len(preceding_ch34) == 0:
        forced_side = "unknown"
    else:
        forced_side = preceding_ch34.iloc[-1]["forced_side"]

    # find closest miniscope frames
    start_idx = (salae_1["Time [s]"] - delay_start_time).abs().idxmin()
    end_idx = (salae_1["Time [s]"] - t11).abs().idxmin()

    trial_number += 1

    delay_trials.append({
        "trial_number": trial_number,
        "forced_side": forced_side,
        "delay_duration_s": round(gap, 3),
        "delay_start_time": delay_start_time,
        "delay_end_time": t11,
        "delay_start_frame": salae_1.loc[start_idx, "Corresponding Miniscope Frame"],
        "delay_end_frame": salae_1.loc[end_idx, "Corresponding Miniscope Frame"]
    })

delay_df_session1 = pd.DataFrame(delay_trials)

delay_df_session1.to_csv("delay_periods_session1.csv", index=False)

print(f"Total delay trials: {len(delay_df_session1)}")
print(f"  5s delays:  {len(delay_df_session1[delay_df_session1.delay_duration_s < 10])}")
print(f"  30s delays: {len(delay_df_session1[delay_df_session1.delay_duration_s > 10])}")
print(f"  Left forced:  {len(delay_df_session1[delay_df_session1.forced_side == 'left'])}")
print(f"  Right forced: {len(delay_df_session1[delay_df_session1.forced_side == 'right'])}")

display(delay_df_session1)

Total delay trials: 12
  5s delays:  6
  30s delays: 6
  Left forced:  6
  Right forced: 6

,trial_number,forced_side,delay_duration_s,delay_start_time,delay_end_time,delay_start_frame,delay_end_frame
0,1,right,4.939,257.067236,262.006716,5412.0,5559.0
1,2,left,30.081,456.053984,486.135164,11333.0,12228.0
2,3,left,5.040,688.783964,693.824014,18258.0,18408.0
3,4,right,30.078,914.421351,944.499123,24965.0,25860.0
4,5,right,29.944,1437.514767,1467.458657,40526.0,41416.0
5,6,left,5.040,1834.112381,1839.152712,52325.0,52475.0
6,7,right,5.512,2216.492839,2222.004723,63703.0,63867.0
7,8,left,30.179,2432.284365,2462.463806,70124.0,71022.0
8,9,left,5.511,2819.269724,2824.780927,81623.0,81787.0
9,10,left,30.579,3197.520441,3228.098971,92877.0,93780.0
10,11,right,30.514,3541.082110,3571.596414,103093.0,104001.0
11,12,right,5.109,3808.929401,3814.038569,111062.0,111214.0

In [27]:
# --- Load aligned salae session 2 ---

salae_2 = pd.read_csv('salaeSamplesMiniscopeRecording_2.csv')

# --- Find Ch11 rising edges ---

ch11_rises = salae_2[
    (salae_2["Channel 11"] == 1) & (salae_2["Channel 11"].shift(1) == 0)
]["Time [s]"].values

# --- Find Ch6 falling edges (delay start) ---

ch6_falling = salae_2[
    (salae_2["Channel 6"] == 0) & (salae_2["Channel 6"].shift(1) == 1)
]["Time [s]"].values

# --- Find last Ch3 or Ch4 rising edge before each Ch6 falling edge ---

ch3_rising = salae_2[
    (salae_2["Channel 3"] == 1) & (salae_2["Channel 3"].shift(1) == 0)
][["Time [s]"]].copy()
ch3_rising["forced_side"] = "left"

ch4_rising = salae_2[
    (salae_2["Channel 4"] == 1) & (salae_2["Channel 4"].shift(1) == 0)
][["Time [s]"]].copy()
ch4_rising["forced_side"] = "right"

ch34_rising = pd.concat([ch3_rising, ch4_rising]).sort_values("Time [s]")

# --- For each Ch11 rising edge, find the preceding Ch6 falling edge ---

delay_trials = []
trial_number = 0

for t11 in ch11_rises:
    preceding_ch6 = ch6_falling[ch6_falling < t11]
    if len(preceding_ch6) == 0:
        continue

    delay_start_time = preceding_ch6[-1]
    gap = t11 - delay_start_time

    if 4 < gap < 8:
        delay_type = 5
    elif 25 < gap < 35:
        delay_type = 30
    else:
        continue

    preceding_ch34 = ch34_rising[ch34_rising["Time [s]"] < delay_start_time]
    if len(preceding_ch34) == 0:
        forced_side = "unknown"
    else:
        forced_side = preceding_ch34.iloc[-1]["forced_side"]

    start_idx = (salae_2["Time [s]"] - delay_start_time).abs().idxmin()
    end_idx = (salae_2["Time [s]"] - t11).abs().idxmin()

    trial_number += 1

    delay_trials.append({
        "trial_number": trial_number,
        "forced_side": forced_side,
        "delay_duration_s": round(gap, 3),
        "delay_start_time": delay_start_time,
        "delay_end_time": t11,
        "delay_start_frame": salae_2.loc[start_idx, "Corresponding Miniscope Frame"],
        "delay_end_frame": salae_2.loc[end_idx, "Corresponding Miniscope Frame"]
    })

delay_df_session2 = pd.DataFrame(delay_trials)

delay_df_session2.to_csv("delay_periods_session2.csv", index=False)

print(f"Total delay trials: {len(delay_df_session2)}")
print(f"  5s delays:  {len(delay_df_session2[delay_df_session2.delay_duration_s < 10])}")
print(f"  30s delays: {len(delay_df_session2[delay_df_session2.delay_duration_s > 10])}")
print(f"  Left forced:  {len(delay_df_session2[delay_df_session2.forced_side == 'left'])}")
print(f"  Right forced: {len(delay_df_session2[delay_df_session2.forced_side == 'right'])}")

display(delay_df_session2)

Total delay trials: 11
  5s delays:  6
  30s delays: 5
  Left forced:  5
  Right forced: 6

,trial_number,forced_side,delay_duration_s,delay_start_time,delay_end_time,delay_start_frame,delay_end_frame
0,1,right,5.175,5190.883394,5196.058886,23844,23998
1,2,right,30.145,5311.197628,5341.342166,27424,28321
2,3,left,5.576,5457.423866,5462.999699,31775,31941
3,4,right,5.949,5702.181072,5708.129690,39058,39235
4,5,right,30.513,5857.313771,5887.827213,43665,44573
5,6,left,5.343,6171.537747,6176.880679,53012,53171
6,7,left,30.550,6510.161830,6540.711520,63088,63997
7,8,right,30.145,7153.704192,7183.849626,82202,83099
8,9,right,5.578,7512.327423,7517.904941,92873,93039
9,10,left,30.012,7861.569125,7891.580924,103265,104158
10,11,left,4.941,8022.647819,8027.588329,108058,108205

In [29]:
## load calcium traces 

calciumData = pd.read_table('/Users/johnmarshall/Documents/Analysis/miniscope_analysis/miniscope_T_maze/m328/LF_analysis/328_C_traces_filtered_origHz.csv', delimiter=',')

In [30]:
calciumData

,Unnamed: 0,cell_1,cell_2,cell_4,cell_5,cell_8,cell_9,cell_10,cell_11,cell_12,...,cell_299,cell_300,cell_302,cell_303,cell_304,cell_305,cell_306,cell_307,cell_308,cell_309
0,0 days 00:00:00,-0.605606,7.869244,-0.499119,-0.595185,-0.342970,-0.549936,-0.572430,3.416981,-0.633596,...,-0.485753,-0.642576,0.610223,3.361113,1.005590,1.168537,0.691617,-0.434580,-0.647135,1.614950
1,0 days 00:00:00.050000,-0.605606,1.124798,0.222773,-0.595185,-0.153463,-0.549936,-0.572430,1.045004,-0.633596,...,-0.485753,2.017369,-0.697508,2.048084,-0.660291,-0.692100,11.914185,-0.499190,-0.647135,-0.664706
2,0 days 00:00:00.100000,-0.605606,2.954716,2.732061,0.330279,-0.342970,-0.549936,-0.572430,2.344835,-0.633596,...,-0.485753,1.782693,-0.593100,0.438445,12.444121,-0.692100,-0.274542,-0.383015,-0.647135,-0.436779
3,0 days 00:00:00.150000,-0.605606,1.204970,1.029710,-0.547890,-0.342970,-0.549936,-0.572430,-0.423562,1.135043,...,-0.485753,-0.642576,0.288491,-0.248011,1.304544,-0.692100,-0.632893,-0.591934,-0.647135,0.681317
4,0 days 00:00:00.200000,-0.605606,-0.534428,-0.655705,-0.160419,-0.342970,-0.549936,-0.158138,0.088094,-0.633596,...,-0.485753,-0.642576,-0.697508,-0.654395,-0.679802,-0.692100,-0.632893,-0.043017,0.159067,-0.125261
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115229,0 days 01:36:01.450000,1.571383,-0.340058,0.455599,-0.595185,-0.091074,-0.549936,0.285368,-0.510275,1.347199,...,0.304031,-0.642576,0.980106,-0.654395,-0.026120,0.732135,-0.387334,-0.591934,-0.647135,-0.664706
115230,0 days 01:36:01.500000,0.339203,0.357402,0.508813,0.213098,0.041844,-0.549936,-0.572430,-0.534254,-0.633596,...,-0.485753,0.078786,0.950376,0.721136,0.187030,-0.623183,-0.632893,1.214719,-0.647135,0.145100
115231,0 days 01:36:01.550000,-0.605606,-0.534428,-0.655705,-0.595185,-0.342970,-0.549936,-0.035254,0.489156,1.387969,...,0.587985,-0.642576,0.442585,-0.654395,-0.679802,-0.610731,-0.632893,1.453986,-0.647135,-0.664706
115232,0 days 01:36:01.600000,-0.424812,0.123940,-0.655705,-0.529656,0.460344,0.522914,0.400651,-0.534254,-0.633596,...,-0.016655,-0.642576,0.593043,-0.654395,-0.679802,-0.537649,-0.081534,0.555559,-0.647135,1.742963
115233,0 days 01:36:01.650000,-0.605606,-0.330434,-0.043612,1.016247,-0.342970,-0.397990,0.382005,-0.534254,-0.333364,...,-0.485753,-0.642576,-0.697508,0.330757,-0.679802,0.788647,-0.632893,-0.360789,-0.242663,-0.664706